services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-reverse-proxy .
  - docker tag udagram-api-reverse-proxy "$DOCKER_USERNAME"/udagram-api-reverse-proxy:latest #added the correct ref

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME"/udagram-api-reverse-proxy
